param([string]$ModelPath = "")
$ErrorActionPreference="Stop";Set-StrictMode -Version Latest
$Here=Split-Path -Parent $MyInvocation.MyCommand.Path
$Cfg=Get-Content (Join-Path $Here "config\p0_target.json") -Raw -Encoding UTF8 | ConvertFrom-Json
$P7L=Get-Content (Join-Path $Here "inputs\p7l_summary.authoritative.json") -Raw -Encoding UTF8 | ConvertFrom-Json
$OutDir=Join-Path $Here "results";$ResultPath=Join-Path $OutDir "p7m_profile_results.json";$SummaryPath=Join-Path $OutDir "p7m_summary.json";$ShaderDir=Join-Path $Here "compiled_shaders";$ExePath=Join-Path $Here "arcllm_p7m.exe";New-Item -ItemType Directory -Force -Path $OutDir|Out-Null
Write-Host "=== ArcLLM P7-M - post-gateup-fusion re-profile ===";Write-Host ""
& py -3 (Join-Path $Here "tests\test_p7m_package.py");if($LASTEXITCODE -ne 0){throw "P7-M package audit failed before execution."}
if(-not $ModelPath){$ModelPath=$Cfg.model_path};Write-Host "Model: $ModelPath";if(-not(Test-Path $ModelPath)){throw "Frozen model not found: $ModelPath"};$TargetHash=(Get-FileHash -Algorithm SHA256 $ModelPath).Hash.ToUpperInvariant();if($TargetHash -ne $Cfg.sha256){throw "Target SHA256 mismatch"};Write-Host "Target SHA256: PASS"
powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $Here "tools\compile_p7m_shaders.ps1");if($LASTEXITCODE -ne 0){exit $LASTEXITCODE};$ProvPath=Join-Path $OutDir "shader_provenance.json";if(-not(Test-Path -LiteralPath $ProvPath)){throw "P7-M shader provenance missing after compile"};$ProvObj=Get-Content -LiteralPath $ProvPath -Raw -Encoding UTF8|ConvertFrom-Json;if($ProvObj.schema -ne "arcllm.p7m.shader_provenance.v1" -or @($ProvObj.compiled).Count -ne 16){throw "P7-M shader provenance verification failed before execution"}
powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $Here "tools\build_p7m.ps1");if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}
$Stdout=Join-Path $OutDir "p7m.stdout.txt";$Stderr=Join-Path $OutDir "p7m.stderr.txt";Remove-Item $Stdout,$Stderr,$ResultPath,$SummaryPath -ErrorAction SilentlyContinue
$Proc=Start-Process -FilePath $ExePath -ArgumentList @("--model",$ModelPath,"--shader-dir",$ShaderDir,"--out",$ResultPath) -NoNewWindow -Wait -PassThru -RedirectStandardOutput $Stdout -RedirectStandardError $Stderr
if(Test-Path $Stdout){Get-Content $Stdout};if(Test-Path $Stderr){$ErrText=Get-Content $Stderr -Raw;if($ErrText){Write-Host "stderr saved: results\p7m.stderr.txt"}}
if(-not(Test-Path $ResultPath)){throw "P7-M did not create result JSON"};$ResultObj=Get-Content $ResultPath -Raw -Encoding UTF8|ConvertFrom-Json;$PpTop=$ResultObj.prefill_profile.categories|Sort-Object chain_share -Descending|Select-Object -First 1;$TgTop=$ResultObj.decode_profile.categories|Sort-Object chain_share -Descending|Select-Object -First 1
$SummaryObj=[ordered]@{schema="arcllm.p7m.summary.v1";target_sha256=$TargetHash;process_exit_code=$Proc.ExitCode;status=$ResultObj.status;p7l_optimized_pp512_tok_s=$P7L.optimized_pp512_tok_s;p7l_pp512_speedup=$P7L.pp512_wall_speedup;timestamp_valid_bits=$ResultObj.prefill_profile.timestamp_valid_bits;optimized_prefill_profile_wall_ms=$ResultObj.prefill_profile.wall_ms;optimized_prefill_top_category=$PpTop.name;optimized_prefill_top_share=$PpTop.chain_share;optimized_prefill_barrier_unattributed_share=($ResultObj.prefill_profile.barrier_or_unattributed_ticks/$ResultObj.prefill_profile.chain_ticks);decode_profile_wall_ms=$ResultObj.decode_profile.wall_ms;decode_top_category=$TgTop.name;decode_top_share=$TgTop.chain_share;decode_barrier_unattributed_share=($ResultObj.decode_profile.barrier_or_unattributed_ticks/$ResultObj.decode_profile.chain_ticks);p7m_gate_pass=$ResultObj.p7m_gate.pass;p7_closed=$ResultObj.p7m_gate.p7_closed}
$SummaryObj|ConvertTo-Json -Depth 8|Set-Content -Encoding UTF8 $SummaryPath
Write-Host "";Write-Host "Result:";Write-Host "  results\shader_provenance.json";Write-Host "  results\p7m_profile_results.json";Write-Host "  results\p7m_summary.json";if(($Proc.ExitCode -ne 0)-or(-not $ResultObj.p7m_gate.pass)){exit 20};exit 0
