param()
$ErrorActionPreference="Stop";Set-StrictMode -Version Latest
$Here=Split-Path -Parent $MyInvocation.MyCommand.Path;$Root=Split-Path -Parent $Here;$Tools=Join-Path $Root "tools\glslang-16.5.0";$ZipPath=Join-Path $Root "tools\glslang-16.5.0.zip";$Url="https://github.com/KhronosGroup/glslang/releases/download/16.5.0/glslang-16.5.0-windows-x86_64-release.zip";$Expected="06B71298B750268C127F2EE7AE0EF7525E2068120C6C8A3A08B2F58CA6F325CE";$Exe=Join-Path $Tools "bin\glslang.exe";$OutDir=Join-Path $Root "compiled_shaders";$ProvPath=Join-Path $Root "results\shader_provenance.json"
New-Item -ItemType Directory -Force -Path (Split-Path $ZipPath -Parent),$OutDir,(Join-Path $Root "results")|Out-Null
if(-not(Test-Path $Exe)){Write-Host "Downloading pinned glslang 16.5.0...";Invoke-WebRequest -UseBasicParsing -Uri $Url -OutFile $ZipPath;$AssetHash=(Get-FileHash -Algorithm SHA256 $ZipPath).Hash.ToUpperInvariant();if($AssetHash -ne $Expected){throw "glslang asset SHA mismatch"};if(Test-Path $Tools){Remove-Item -Recurse -Force $Tools};Expand-Archive -Path $ZipPath -DestinationPath $Tools -Force}
$Names=@("p8c_embedding_q4k_segmented_probe.comp","p8c_lmhead_q6k_segmented_probe.comp");$CompiledList=@()
foreach($Name in $Names){$SrcPath=Join-Path $Root ("shaders\"+$Name);$SpvPath=Join-Path $OutDir ([IO.Path]::GetFileNameWithoutExtension($Name)+".spv");Write-Host "Compile $Name";& $Exe -V --target-env vulkan1.2 -S comp -o $SpvPath $SrcPath;if($LASTEXITCODE -ne 0){exit $LASTEXITCODE};$CompiledList += [ordered]@{source=$Name;source_sha256=(Get-FileHash -Algorithm SHA256 $SrcPath).Hash.ToUpperInvariant();spv=[IO.Path]::GetFileName($SpvPath);spv_sha256=(Get-FileHash -Algorithm SHA256 $SpvPath).Hash.ToUpperInvariant();spv_bytes=(Get-Item $SpvPath).Length}}
$ProvObj=[ordered]@{schema="arcllm.p8c.shader_provenance.v1";compiler="glslang.exe";compiler_release="16.5.0";compiler_asset="glslang-16.5.0-windows-x86_64-release.zip";compiler_asset_url=$Url;compiler_asset_sha256=$Expected;target_env="vulkan1.2";compiled=$CompiledList}
$ProvJson=$ProvObj|ConvertTo-Json -Depth 8;[IO.File]::WriteAllText($ProvPath,$ProvJson,(New-Object Text.UTF8Encoding($false)));$Check=Get-Content $ProvPath -Raw -Encoding UTF8|ConvertFrom-Json;if(@($Check.compiled).Count -ne 2){throw "P8-C shader provenance count mismatch"};foreach($Item in $Check.compiled){$Src=Join-Path $Root ("shaders\"+$Item.source);$Spv=Join-Path $OutDir $Item.spv;if((Get-FileHash -Algorithm SHA256 $Src).Hash.ToUpperInvariant() -ne $Item.source_sha256){throw "P8-C source provenance mismatch"};if((Get-FileHash -Algorithm SHA256 $Spv).Hash.ToUpperInvariant() -ne $Item.spv_sha256){throw "P8-C SPIR-V provenance mismatch"}}
Write-Host "P8-C shader compile: PASS"
