param()
$ErrorActionPreference="Stop";Set-StrictMode -Version Latest
$Here=Split-Path -Parent $MyInvocation.MyCommand.Path;$Root=Split-Path -Parent $Here;$Tools=Join-Path $Root "tools\glslang-16.5.0";$ZipPath=Join-Path $Root "tools\glslang-16.5.0.zip";$Url="https://github.com/KhronosGroup/glslang/releases/download/16.5.0/glslang-16.5.0-windows-x86_64-release.zip";$Expected="06B71298B750268C127F2EE7AE0EF7525E2068120C6C8A3A08B2F58CA6F325CE";$Exe=Join-Path $Tools "bin\glslang.exe";$OutDir=Join-Path $Root "compiled_shaders";$ProvPath=Join-Path $Root "results\shader_provenance.json"
New-Item -ItemType Directory -Force -Path (Split-Path $ZipPath -Parent),$OutDir,(Join-Path $Root "results")|Out-Null
if(-not(Test-Path $Exe)){Write-Host "Downloading pinned glslang 16.5.0...";Invoke-WebRequest -UseBasicParsing -Uri $Url -OutFile $ZipPath;$AssetHash=(Get-FileHash -Algorithm SHA256 $ZipPath).Hash.ToUpperInvariant();if($AssetHash -ne $Expected){throw "glslang asset SHA mismatch"};if(Test-Path $Tools){Remove-Item -Recurse -Force $Tools};Expand-Archive -Path $ZipPath -DestinationPath $Tools -Force}
Write-Host "Shader compiler: $Exe";$CompiledList=@();$Names=@("p7_add.comp","p7_attention_kv_online.comp","p7_attention_prefill_online.comp","p7_embedding_q6k.comp","p7_kv_store.comp","p7_lmhead_q6k_chunk.comp","p7_q4k_gemm_2d.comp","p7_q6k_gemm_2d.comp","p7_rmsnorm_seq.comp","p7_rope_seq.comp","p7_swiglu.comp","p7c_ffn_q4k_tiled.comp","p7c_ffn_q6k_tiled.comp","p7g_ffn_q4k_tiled16.comp","p7g_ffn_q6k_tiled16.comp","p7i_ffn_q4k_tiled32.comp","p7i_ffn_q6k_tiled32.comp")
foreach($Name in $Names){$SrcPath=Join-Path $Root ("shaders\"+$Name);$SpvPath=Join-Path $OutDir ([IO.Path]::GetFileNameWithoutExtension($Name)+".spv");Write-Host "Compile $Name";& $Exe -V --target-env vulkan1.2 -S comp -o $SpvPath $SrcPath;if($LASTEXITCODE -ne 0){exit $LASTEXITCODE};$CompiledList += [ordered]@{source=$Name;source_sha256=(Get-FileHash -Algorithm SHA256 $SrcPath).Hash.ToUpperInvariant();spv=[IO.Path]::GetFileName($SpvPath);spv_sha256=(Get-FileHash -Algorithm SHA256 $SpvPath).Hash.ToUpperInvariant();spv_bytes=(Get-Item $SpvPath).Length}}
$ProvObj=[ordered]@{schema="arcllm.p7i.shader_provenance.v1";compiler="glslang.exe";compiler_release="16.5.0";compiler_asset="glslang-16.5.0-windows-x86_64-release.zip";compiler_asset_url=$Url;compiler_asset_sha256=$Expected;target_env="vulkan1.2";compiled=$CompiledList}
$ProvJson=$ProvObj|ConvertTo-Json -Depth 8;[IO.File]::WriteAllText($ProvPath,$ProvJson,(New-Object Text.UTF8Encoding($false)));if(-not(Test-Path -LiteralPath $ProvPath)){throw "shader provenance materialization failed"};$ProvCheck=Get-Content -LiteralPath $ProvPath -Raw -Encoding UTF8|ConvertFrom-Json;if($ProvCheck.compiled.Count -ne $Names.Count){throw "shader provenance count mismatch"};foreach($Item in $ProvCheck.compiled){$CheckSrc=Join-Path $Root ("shaders\"+$Item.source);$CheckSpv=Join-Path $OutDir $Item.spv;if((Get-FileHash -Algorithm SHA256 $CheckSrc).Hash.ToUpperInvariant() -ne $Item.source_sha256){throw "source provenance hash mismatch"};if((Get-FileHash -Algorithm SHA256 $CheckSpv).Hash.ToUpperInvariant() -ne $Item.spv_sha256){throw "SPIR-V provenance hash mismatch"}}
Write-Host "Shader provenance verified: $ProvPath";Write-Host "Shader compile: PASS"